# Generated by Django 3.0.4 on 2020-03-17 22:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('VolunteerID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50, null=True)),
                ('Last_Name', models.CharField(max_length=50, null=True)),
                ('Phone', models.CharField(max_length=10, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acceptance_Status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=50, null=True)),
                ('Date_Form_Submitted', models.DateField(auto_now_add=True, null=True)),
                ('Citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firedepartment.Citizen')),
            ],
        ),
    ]
