# Generated by Django 3.0.4 on 2020-04-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firedepartment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='VolunteerID',
            new_name='CitizenID',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='Acceptance_Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=50, null=True),
        ),
    ]
